-- AlterTable
ALTER TABLE "ParticularsAcademic" ALTER COLUMN "cgpa" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Sem1" ALTER COLUMN "cgpa" SET DEFAULT 0,
ALTER COLUMN "cgpa" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Sem2" ALTER COLUMN "cgpa" SET DEFAULT 0,
ALTER COLUMN "cgpa" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Sem3" ALTER COLUMN "cgpa" SET DEFAULT 0,
ALTER COLUMN "cgpa" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Sem4" ALTER COLUMN "cgpa" SET DEFAULT 0,
ALTER COLUMN "cgpa" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Sem5" ALTER COLUMN "cgpa" SET DEFAULT 0,
ALTER COLUMN "cgpa" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Sem6" ALTER COLUMN "cgpa" SET DEFAULT 0,
ALTER COLUMN "cgpa" SET DATA TYPE DOUBLE PRECISION;
